大森の記事を追加
yumemi-inc/daigirin-2024-2 pull request #27
Opened 2024-10-10 18:55 UTC by OHMORIYUSUKE

[ebook.pdf](https://github.com/user-attachments/files/17332917/ebook.pdf)

ローカル環境でtextlintが動作しませんでした。
```
 => ERROR [lint 4/4] RUN yarn install --frozen-lockfile && yarn cache clean                                                      0.5s
------
 > [lint 4/4] RUN yarn install --frozen-lockfile && yarn cache clean:
0.432 error This project's package.json defines "packageManager": "yarn@4.4.1". However the current global version of Yarn is 1.22.22.
0.432 
0.432 Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19.
0.432 Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out https://yarnpkg.com/corepack.
------
failed to solve: process "/bin/sh -c yarn install --frozen-lockfile && yarn cache clean" did not complete successfully: exit code: 1
make: *** [lint] Error 17
```

2024-10-10 18:59 UTC, OHMORIYUSUKE commented
textlintは直します

2024-10-11 01:52 UTC, mitsuharu requested changes
6ページ予定でしたが、8ページになってます。6ページに収めることはできますか？

2024-10-11 02:07 UTC, OHMORIYUSUKE commented
@mitsuharu 
すみません。6ページにします🙇

2024-10-11 02:14 UTC, OHMORIYUSUKE commented
[ebook.pdf](https://github.com/user-attachments/files/17336718/ebook.pdf)
6ページに収まるように修正しました。

2024-10-11 04:00 UTC, mitsuharu reviewed
`[abc](https://...)` でリンク可能になっているのは問題ないですが、紙版ではタップできないのでURLが分からない、電子版ではマウスオーバーしないと気づかないので、URLを明確に紹介したい場合は注釈などで説明を入れるとよいです

2024-10-11 04:00 UTC, mitsuharu commented on book/manuscripts/omori.md
> +さまざまな勉強会の主催や運営しています。これらの勉強会の募集などは connpass[^connpass] というサービスを利用して行っています。[ゆめみの社外向け勉強会](https://yumemi.connpass.com/)は 8 回、プライベートでは 18 回開催してきました。
紙版はURLが分からない、電子版はリンク可能かマウスオーバーしないと分からないので、注釈でURLを表示するとよいです。ページ数が限られているので、共有したいURLのみを注釈にするとよいです

2024-10-11 04:00 UTC, mitsuharu commented on book/manuscripts/omori.md
> +都心では珍しい、ノンジャンル技術系 LT イベントです。他の都心の勉強会ではテーマが決められている勉強会がほとんどですが、@godan09 さん曰く、この勉強会は「研究室の中の雑談や技術サークル部屋の雑談」のような勉強会を目指しているそうです。
悩むけど、@godan09さんを一度リンク可能にしたら、以降もリンク可能にするかですかね。もしくは注釈で一回切りの説明にする

2024-10-11 04:00 UTC, mitsuharu commented on book/manuscripts/omori.md
> +勉強会に参加しつつ、アニメ好きのエンジニアと交流できる場が欲しいと思い続けていたところで、とあるスライドをみつけました。にしこりさぶろ〜([@subroh_0508](https://x.com/subroh_0508))さんが発表された「[自己効力感を二次元アイドル作品から得ながら社会人としての成長を超加速させる](https://speakerdeck.com/subroh0508/zi-j
このスライドURLは注釈で書くとよさそう。

2024-10-11 04:00 UTC, mitsuharu commented on book/manuscripts/omori.md
> +    [タイミー広場を技術コミュニティにオープン化します｜かわまた／DevRel](https://note.com/r_kawamata/n/nb3157e12819c)
[must]
この注釈は分ける。タイトルはページに余裕があればいいけど、厳しいのでURLのみで。

```
オイシックス・ラ・大地さんやタイミーさんはブログなどで紹介しています。[^oisix] [^timee]

[^oisix]: https://creators.oisixradaichi.co.jp/entry/2023/11/08/120716
[^timee]: https://note.com/r_kawamata/n/nb3157e12819c
```

2024-10-11 04:00 UTC, mitsuharu commented on book/manuscripts/omori.md
> +イベントページに会の趣旨や会のテーマのベースになっている、にしこりさぶろ〜([@subroh_0508](https://x.com/subroh_0508))さんの「[自己効力感を二次元アイドル作品から得ながら社会人としての成長を超加速させる](https://speakerdeck.com/subroh0508/zi-ji-xiao-li-gan-woer-ci-yuan-aidoruzuo
ここもスライド説明なので、URLを注釈

2024-10-11 05:25 UTC, OHMORIYUSUKE commented
@mitsuharu 
レビューありがとうございます。URLを注釈に書くように修正しました。

2024-10-11 05:44 UTC, mitsuharu reviewed
同じ注釈を多用しているので、文章内と文末の注釈番号がずれています。注釈の利用は１タグ１回で、Xアカウントとかは一度紹介すれば途中で変わることがないので一度で良いです。

あと、細かいですが `xxx [^注釈1] さん`, `yyy さん[^注釈2] ` と注釈の位置が文書で異なるのが気になりました。どちらが正しいかは個人のセンスかなと思いますが、統一したほうが無難かなと思いました

2024-10-11 05:44 UTC, mitsuharu commented on book/manuscripts/omori.md
> +都心では珍しい、ノンジャンル技術系 LT イベントです。他の都心の勉強会ではテーマが決められている勉強会がほとんどですが、@godan09[^godan09] さん曰く、この勉強会は「研究室の中の雑談や技術サークル部屋の雑談」のような勉強会を目指しているそうです。
`[^godan09]` が2回の利用になっているので注釈番号の計算がずれています。godan09さんの説明は上の文章でしてるので、2回目の注釈は不要です。文中の注釈番号と、文末の注釈がずれているので、他に多用しているところがありそうです。

2024-10-11 07:06 UTC, OHMORIYUSUKE commented on book/manuscripts/omori.md
> +都心では珍しい、ノンジャンル技術系 LT イベントです。他の都心の勉強会ではテーマが決められている勉強会がほとんどですが、@godan09[^godan09] さん曰く、この勉強会は「研究室の中の雑談や技術サークル部屋の雑談」のような勉強会を目指しているそうです。
ありがとうございます。注釈を複数回使っていたところを修正しました。

[ebook.pdf](https://github.com/user-attachments/files/17338972/ebook.pdf)

2024-10-11 07:14 UTC, mitsuharu approved these changes

2024-10-11 09:13 UTC, merged